import createClient from "openapi-fetch";
// import type { paths } from "../../../my_schema"; // generated by openapi-typescript
import type { paths } from "../../../my_schema2"; // generated by openapi-typescript

const client = createClient<paths>({
  baseUrl: "http://localhost:3000/",
  credentials: "include",
});

const {
  data, // only present if 2XX response
  error, // only present if 4XX or 5XX response
} = await client.GET("/api/v1/user/me", {
  params: {},
});

console.log("api fetch:");
console.log("data:", data);
console.log("error:", error);

// await client.PUT("/blogposts", {
//   body: {
//     title: "My New Post",
//   },
// });

const {
  data: data2, // only present if 2XX response
  error: error2, // only present if 4XX or 5XX response
} = await client.POST("/api/v1/user/me", {
  params: {},
  body: {
    // firstName: `rand-${Math.random()}`
    firstName: `rand-${Math.random()}`,
  },
});

export function useApi() {}
