/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cats example
 * The cats API description
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface User { [key: string]: unknown }

export interface UpdateUserDto {
  firstName: string;
}

export interface RegisterEmailDto {
  email: string;
  /** @minLength 4 */
  password: string;
  firstName?: string;
}

export type AuthControllerCallbackV1Params = {
code: string;
};

export const appControllerGetHelloV1 = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/v1/app/hi`,options
    );
  }

export const userControllerMeV1 = <TData = AxiosResponse<User | User[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/v1/user/me`,options
    );
  }

export const userControllerUpdateV1 = <TData = AxiosResponse<void>>(
    updateUserDto: UpdateUserDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/v1/user/me`,
      updateUserDto,options
    );
  }

export const authControllerCallbackV1 = <TData = AxiosResponse<void>>(
    provider: string,
    params: AuthControllerCallbackV1Params, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/v1/auth/oauth/callback/${provider}`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const authControllerRegisterWithEmailV1 = <TData = AxiosResponse<void>>(
    registerEmailDto: RegisterEmailDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/v1/auth/register/email`,
      registerEmailDto,options
    );
  }

export type AppControllerGetHelloV1Result = AxiosResponse<void>
export type UserControllerMeV1Result = AxiosResponse<User | User[]>
export type UserControllerUpdateV1Result = AxiosResponse<void>
export type AuthControllerCallbackV1Result = AxiosResponse<void>
export type AuthControllerRegisterWithEmailV1Result = AxiosResponse<void>
