/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * movement
 * The cats API description
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';






export const appControllerGetHelloV1 = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/api/v1/app/hi`,options
    );
  }




export const getAppControllerGetHelloV1QueryKey = () => {
    return [
    `/api/v1/app/hi`
    ] as const;
    }

    
export const getAppControllerGetHelloV1QueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetHelloV1>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHelloV1>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppControllerGetHelloV1QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetHelloV1>>> = ({ signal }) => appControllerGetHelloV1({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHelloV1>>, TError, TData> & { queryKey: QueryKey }
}

export type AppControllerGetHelloV1QueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetHelloV1>>>
export type AppControllerGetHelloV1QueryError = AxiosError<unknown>



export function useAppControllerGetHelloV1<TData = Awaited<ReturnType<typeof appControllerGetHelloV1>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHelloV1>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAppControllerGetHelloV1QueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



