/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * movement
 * The cats API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  AuthControllerCallbackV1Params,
  RegisterEmailDto
} from './movement.schemas';

import { customInstance } from '../shared/custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const authControllerCallbackV1 = (
    provider: string,
    params: AuthControllerCallbackV1Params,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/auth/oauth/callback/${provider}`, method: 'POST',
        params, signal
    },
      options);
    }
  


export const getAuthControllerCallbackV1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerCallbackV1>>, TError,{provider: string;params: AuthControllerCallbackV1Params}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerCallbackV1>>, TError,{provider: string;params: AuthControllerCallbackV1Params}, TContext> => {

const mutationKey = ['authControllerCallbackV1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerCallbackV1>>, {provider: string;params: AuthControllerCallbackV1Params}> = (props) => {
          const {provider,params} = props ?? {};

          return  authControllerCallbackV1(provider,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerCallbackV1MutationResult = NonNullable<Awaited<ReturnType<typeof authControllerCallbackV1>>>
    
    export type AuthControllerCallbackV1MutationError = unknown

    export const useAuthControllerCallbackV1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerCallbackV1>>, TError,{provider: string;params: AuthControllerCallbackV1Params}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerCallbackV1>>,
        TError,
        {provider: string;params: AuthControllerCallbackV1Params},
        TContext
      > => {

      const mutationOptions = getAuthControllerCallbackV1MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const authControllerRegisterWithEmailV1 = (
    registerEmailDto: RegisterEmailDto,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/auth/register/email`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerEmailDto, signal
    },
      options);
    }
  


export const getAuthControllerRegisterWithEmailV1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRegisterWithEmailV1>>, TError,{data: RegisterEmailDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerRegisterWithEmailV1>>, TError,{data: RegisterEmailDto}, TContext> => {

const mutationKey = ['authControllerRegisterWithEmailV1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerRegisterWithEmailV1>>, {data: RegisterEmailDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerRegisterWithEmailV1(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerRegisterWithEmailV1MutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRegisterWithEmailV1>>>
    export type AuthControllerRegisterWithEmailV1MutationBody = RegisterEmailDto
    export type AuthControllerRegisterWithEmailV1MutationError = unknown

    export const useAuthControllerRegisterWithEmailV1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRegisterWithEmailV1>>, TError,{data: RegisterEmailDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerRegisterWithEmailV1>>,
        TError,
        {data: RegisterEmailDto},
        TContext
      > => {

      const mutationOptions = getAuthControllerRegisterWithEmailV1MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    