/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * movement
 * The cats API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AuthControllerCallbackV1Params,
  RegisterEmailDto
} from './movement.schemas';






export const authControllerCallbackV1 = (
    provider: string,
    params: AuthControllerCallbackV1Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/oauth/callback/${provider}`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getAuthControllerCallbackV1MutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerCallbackV1>>, TError,{provider: string;params: AuthControllerCallbackV1Params}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerCallbackV1>>, TError,{provider: string;params: AuthControllerCallbackV1Params}, TContext> => {

const mutationKey = ['authControllerCallbackV1'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerCallbackV1>>, {provider: string;params: AuthControllerCallbackV1Params}> = (props) => {
          const {provider,params} = props ?? {};

          return  authControllerCallbackV1(provider,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerCallbackV1MutationResult = NonNullable<Awaited<ReturnType<typeof authControllerCallbackV1>>>
    
    export type AuthControllerCallbackV1MutationError = AxiosError<unknown>

    export const useAuthControllerCallbackV1 = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerCallbackV1>>, TError,{provider: string;params: AuthControllerCallbackV1Params}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof authControllerCallbackV1>>,
        TError,
        {provider: string;params: AuthControllerCallbackV1Params},
        TContext
      > => {

      const mutationOptions = getAuthControllerCallbackV1MutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const authControllerRegisterWithEmailV1 = (
    registerEmailDto: RegisterEmailDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/api/v1/auth/register/email`,
      registerEmailDto,options
    );
  }



export const getAuthControllerRegisterWithEmailV1MutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRegisterWithEmailV1>>, TError,{data: RegisterEmailDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerRegisterWithEmailV1>>, TError,{data: RegisterEmailDto}, TContext> => {

const mutationKey = ['authControllerRegisterWithEmailV1'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerRegisterWithEmailV1>>, {data: RegisterEmailDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerRegisterWithEmailV1(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerRegisterWithEmailV1MutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRegisterWithEmailV1>>>
    export type AuthControllerRegisterWithEmailV1MutationBody = RegisterEmailDto
    export type AuthControllerRegisterWithEmailV1MutationError = AxiosError<unknown>

    export const useAuthControllerRegisterWithEmailV1 = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRegisterWithEmailV1>>, TError,{data: RegisterEmailDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof authControllerRegisterWithEmailV1>>,
        TError,
        {data: RegisterEmailDto},
        TContext
      > => {

      const mutationOptions = getAuthControllerRegisterWithEmailV1MutationOptions(options);

      return useMutation(mutationOptions);
    }
    