/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * movement
 * The cats API description
 * OpenAPI spec version: 1.0
 */
export interface User { [key: string]: unknown }

export interface UpdateUserDto {
  firstName: string;
}

export interface RegisterEmailDto {
  email: string;
  /** @minLength 4 */
  password: string;
  firstName?: string;
}

export type AuthControllerCallbackV1Params = {
code: string;
};

