/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * movement
 * The cats API description
 * OpenAPI spec version: 1.0
 */
export interface AuthCredential { [key: string]: unknown }

export interface Session { [key: string]: unknown }

export interface User {
  id: string;
  /** @nullable */
  firstName: string | null;
  createdAt: string;
  updatedAt: string;
  credential: AuthCredential;
  sessions: Session[];
}

export interface UpdateUserDto {
  firstName: string;
}

export interface RegisterEmailDto {
  email: string;
  /** @minLength 4 */
  password: string;
  firstName?: string;
}

export type AuthControllerCallbackV1Params = {
code: string;
};

