/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * movement
 * The cats API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  UpdateUserDto,
  User
} from './movement.schemas';

import { customInstance } from '../shared/custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const userControllerMeV1 = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<User>(
      {url: `/api/v1/user/me`, method: 'GET', signal
    },
      options);
    }
  



export const getUserControllerMeV1QueryKey = () => {
    return [
    `/api/v1/user/me`
    ] as const;
    }

    
export const getUserControllerMeV1QueryOptions = <TData = Awaited<ReturnType<typeof userControllerMeV1>>, TError = number>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerMeV1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserControllerMeV1QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerMeV1>>> = ({ signal }) => userControllerMeV1(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userControllerMeV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserControllerMeV1QueryResult = NonNullable<Awaited<ReturnType<typeof userControllerMeV1>>>
export type UserControllerMeV1QueryError = number


export function useUserControllerMeV1<TData = Awaited<ReturnType<typeof userControllerMeV1>>, TError = number>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerMeV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerMeV1>>,
          TError,
          Awaited<ReturnType<typeof userControllerMeV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerMeV1<TData = Awaited<ReturnType<typeof userControllerMeV1>>, TError = number>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerMeV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerMeV1>>,
          TError,
          Awaited<ReturnType<typeof userControllerMeV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerMeV1<TData = Awaited<ReturnType<typeof userControllerMeV1>>, TError = number>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerMeV1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUserControllerMeV1<TData = Awaited<ReturnType<typeof userControllerMeV1>>, TError = number>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerMeV1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserControllerMeV1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const userControllerUpdateV1 = (
    updateUserDto: UpdateUserDto,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/user/me`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateUserDto, signal
    },
      options);
    }
  


export const getUserControllerUpdateV1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateV1>>, TError,{data: UpdateUserDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateV1>>, TError,{data: UpdateUserDto}, TContext> => {

const mutationKey = ['userControllerUpdateV1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerUpdateV1>>, {data: UpdateUserDto}> = (props) => {
          const {data} = props ?? {};

          return  userControllerUpdateV1(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerUpdateV1MutationResult = NonNullable<Awaited<ReturnType<typeof userControllerUpdateV1>>>
    export type UserControllerUpdateV1MutationBody = UpdateUserDto
    export type UserControllerUpdateV1MutationError = unknown

    export const useUserControllerUpdateV1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateV1>>, TError,{data: UpdateUserDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerUpdateV1>>,
        TError,
        {data: UpdateUserDto},
        TContext
      > => {

      const mutationOptions = getUserControllerUpdateV1MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    