/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * movement
 * The cats API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  UpdateUserDto,
  User
} from './movement.schemas';






export const userControllerMeV1 = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<User | User[]>> => {
    
    
    return axios.default.get(
      `/api/v1/user/me`,options
    );
  }




export const getUserControllerMeV1QueryKey = () => {
    return [
    `/api/v1/user/me`
    ] as const;
    }

    
export const getUserControllerMeV1QueryOptions = <TData = Awaited<ReturnType<typeof userControllerMeV1>>, TError = AxiosError<number>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof userControllerMeV1>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserControllerMeV1QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerMeV1>>> = ({ signal }) => userControllerMeV1({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userControllerMeV1>>, TError, TData> & { queryKey: QueryKey }
}

export type UserControllerMeV1QueryResult = NonNullable<Awaited<ReturnType<typeof userControllerMeV1>>>
export type UserControllerMeV1QueryError = AxiosError<number>



export function useUserControllerMeV1<TData = Awaited<ReturnType<typeof userControllerMeV1>>, TError = AxiosError<number>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof userControllerMeV1>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUserControllerMeV1QueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const userControllerUpdateV1 = (
    updateUserDto: UpdateUserDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/api/v1/user/me`,
      updateUserDto,options
    );
  }



export const getUserControllerUpdateV1MutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateV1>>, TError,{data: UpdateUserDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateV1>>, TError,{data: UpdateUserDto}, TContext> => {

const mutationKey = ['userControllerUpdateV1'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerUpdateV1>>, {data: UpdateUserDto}> = (props) => {
          const {data} = props ?? {};

          return  userControllerUpdateV1(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerUpdateV1MutationResult = NonNullable<Awaited<ReturnType<typeof userControllerUpdateV1>>>
    export type UserControllerUpdateV1MutationBody = UpdateUserDto
    export type UserControllerUpdateV1MutationError = AxiosError<unknown>

    export const useUserControllerUpdateV1 = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateV1>>, TError,{data: UpdateUserDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof userControllerUpdateV1>>,
        TError,
        {data: UpdateUserDto},
        TContext
      > => {

      const mutationOptions = getUserControllerUpdateV1MutationOptions(options);

      return useMutation(mutationOptions);
    }
    